# Generated by Django 6.1 on 2026-09-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_rejection_reason_alter_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cached aggregate average rating from 1.00 to 5.00', max_digits=3),
        ),
        migrations.AddField(
            model_name='course',
            name='review_count',
            field=models.PositiveIntegerField(default=0, help_text='Cached count of visible student reviews'),
        ),
    ]
