# Generated by Django 6.1 on 2026-09-04 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_course_rejection_reason_alter_course_status'),
        ('enrollments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Detailed assignment guidelines, deliverables, and rubric')),
                ('submission_type', models.CharField(choices=[('LINK', 'External Link / URL'), ('FILE', 'File Upload / Document'), ('TEXT', 'Text Response / Code'), ('HYBRID', 'Link & Written Report')], default='LINK', max_length=20)),
                ('max_score', models.PositiveIntegerField(default=100)),
                ('passing_score', models.PositiveIntegerField(default=60)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('is_mandatory', models.BooleanField(default=True, help_text='If true, passing this assignment is strictly required for certificate eligibility')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course')),
                ('subject', models.ForeignKey(blank=True, help_text='Optional curriculum module this assignment belongs to. If null, acts as a course capstone.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='courses.subject')),
            ],
            options={
                'ordering': ['course', 'subject__order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_link', models.URLField(blank=True, default='')),
                ('submission_text', models.TextField(blank=True, default='')),
                ('submission_file', models.FileField(blank=True, null=True, upload_to='assignments/submissions/%Y/%m/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('GRADED', 'Graded'), ('RESUBMISSION_REQUESTED', 'Resubmission Requested')], default='SUBMITTED', max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='enrollments.enrollment')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('assignment', 'trainee')},
            },
        ),
        migrations.CreateModel(
            name='SubmissionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('passed', models.BooleanField(default=False)),
                ('feedback', models.TextField(help_text='Constructive critique, commendations, or guidance on what to improve')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_reviews', to=settings.AUTH_USER_MODEL)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='assignments.assignmentsubmission')),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
    ]
