# Generated by Django 6.1 on 2026-09-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='supabase_uid',
            field=models.UUIDField(blank=True, db_index=True, help_text='Supabase Auth user UUID (primary external identity link)', null=True, unique=True),
        ),
    ]
